version: '3'

services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  app:
    image: searchgymplay/your-springboot-app-image
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - redis
