cloud:
  aws:
    credentials:
      secret-key: FtrO2s8GEapoXp9Ux6I9hlk4GPpuNBmyJ3u/m7Sg
      access-key: AKIA3PSCLOQM4KZGTWEK
    s3:
      bucket: gylike.shop
    region:
      static: ap-northeast-2
    stack:
      auto: 'false'
spring:
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 30

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;MODE=MYSQL;
    username: sa
    password:

  mvc:
    hiddenmethod:
      filter:
        enabled: 'true '
  thymeleaf:
    cache: 'false'
  main:
    allow-bean-definition-overriding: 'true'

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6


  # H2 Setting Info (H2 Console에 접속하기 위한 설정정보 입력)
#  h2:
#    console:
#      enabled: true  # H2 Console을 사용할지 여부 (H2 Console은 H2 Database를 UI로 제공해주는 기능)
#      path: /h2-console  # H2 Console의 Path

  # Mysql 설정
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://team-database1.cjqopg7k8xlv.ap-northeast-2.rds.amazonaws.com:3306/mydb?serverTimezone=UTC&characterEncoding=UTF-8
#    username: admin
#    password: 8teamadmin

# Actuator
management:
  endpoint:
    metrics:
      enabled : true
    prometheus:
      enabled: true

  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, metrics, prometheus, info
        # exclude: env은 Actuator 엔드포인트 중에서 "env"를 제외하겠다는 의미입니다.
        # "env" 엔드포인트는 애플리케이션의 환경 변수를 보여주는 엔드포인트이며,
        # 보안상의 이유로 기본적으로 제외되어 있습니다.
        # 굳이 해둔이유는 누군가
        # include를 "*"로 바꾸었을때를 위한 대비입니다.
        exclude: env

  metrics:
    tags:
      application: Final8TeamProjectApplication


logging:
  level:
    com.example.myapp: DEBUG

#이메일보내는것 설정

mail:
  smtp:
    port: '465'
    starttls:
      enable: 'true'
      required: 'true'
    socketFactory:
      fallback: 'false'
      class: javax.net.ssl.SSLSocketFactory
      port: '465'
    auth: 'true'

AdminMail:
  id: spartafinalproject@gmail.com
  password: wpzfionudzmbhaau

jwt:
  secret:
    key: 7ZWt7ZW0OTntmZTsnbTtjIXtlZzqta3snYTrhIjrqLjshLjqs4TroZzrgpjslYTqsIDsnpDtm4zrpa3tlZzqsJzrsJzsnpDrpbzrp4zrk6TslrTqsIDsnpA=
